import './globals.css';
import { Inter } from 'next/font/google';
import { Header } from './Header/Header';
import { Footer } from './Footer/Footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <header className='flex  items-center justify-center p-2'>
          <Header/>
        </header>
        <main>
        {children}
        </main>
        
          <Footer/>
        
        </body>
    </html>
  )
}
